### ISSUE TITLE
Notifee doesn't build with Android gradle plugin v4+, cannot resolve BuildConfig.VERSION_NAME

### ISSUE THREAD

**Issue by AndrewMorsillo** [notifee/react-native-notifee#143]
I'm trying to use Android gradle plugin 4.1.0-rc01 to generate debug symbols to deploy to play store. When using this version of the gradle plugin Notifee doesn't build.

build.gradle
```
classpath 'com.android.tools.build:gradle:4.1.0-rc01'
```

I have little experience with the Android build system so I apologize if this is something obvious I'm doing wrong.

```
NotifeeInitProvider.java:19: error: cannot find symbol
    configBuilder.setProductVersion(BuildConfig.VERSION_NAME);
                                               ^
  symbol:   variable VERSION_NAME
  location: class BuildConfig
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':notifee_react-native:compileDebugJavaWithJavac'.
```

**Comment by mikehardy** [comment]
Nice to have a bug report for an unreleased version, we may have something to fix there, but does it build with gradle plugin 4.0.1 (current stable) - it seems to for me?

**Comment by mikehardy** [comment]
Breaking change between gradle plugin 4.0 and 4.1, issue tracked here, with possible workaround:
https://issuetracker.google.com/issues/158695880

**Comment by mikehardy** [comment]
I should have a patch for this shortly. Test compiling now.

**Comment by mikehardy** [comment]
Here's a patch for you @AndrewMorsillo - it works for me with android gradle plugin 4.0.1 and 4.1.0-rc02 when put into the "patches" directory and applied via https://github.com/ds300/patch-package

[notifee-android-gradle-plugin-4.1.0.zip](https://github.com/notifee/react-native-notifee/files/5179892/notifee-android-gradle-plugin-4.1.0.zip)

I'll post the official PR in a moment and this will be released soon I am sure, but I'd appreciate if you could confirm it works for you as well?

Cheers!

**Comment by AndrewMorsillo** [comment]
@mikehardy Patch works great, thanks! Now that it build with gradle plugin 4.1.0-rc it still doesn't run but those issues are unrelated to notifee.

**Comment by mikehardy** [comment]
Sorry to hear your project still isn't happy with 4.1.0 but glad we're no longer your blocker. We release pretty frequently here so it shouldn't be long before the patch is official (and patch-package will kindly alert you, so no worries) Cheers :-)
