### ISSUE TITLE
Cocoapods 1.10+ required / 1.9 does not work (was Missing [CP] Embed Pods Frameworks)

### ISSUE THREAD

**Issue by IsaacIsrael** [notifee/react-native-notifee#230]
When I updated for version 0.16.0.  It  deletes the Embed Pods Frameworks from the `project.pbxproj` when I  run `pod install`

**Comment by helenaford** [comment]
Interesting  🤔  Thanks for reporting the issue. Do you have details of the Xcode version you're using? In `v0.16.0` we changed how the library is bundled to support Apple Silicon and Mac Catalyst builds, which may have caused this. Will mark this as 'needs-review' so it's bumped up to the top of the queue.

**Comment by IsaacIsrael** [comment]
I am using XCode 12.2

**Comment by mikehardy** [comment]
This sounds like it could be a cocoapods issue. We build and test with current stable - 1.10 (actually 1.10.1 as of this typing) and cocoapods is responsible for adding and removing those, it is not something we do. It is affected by our switch from .framework to .xcframework though. I suggest updating (if you have not already) to 1.10.1, maybe trying a `pod deintegrate` then a `pod install` and see if it persists

We have a continuous integration system that tests this stuff all the time plus https://github.com/mikehardy/rnfbdemo/blob/master/notifee-demo.sh which builds a test rig from scratch and those were all working with `@notifee/react-native` >= 0.16.0 so I suspect this is something subtle

**Comment by IsaacIsrael** [comment]
Hey, @mikehardy thank you for the feedback. It was what I thought in the first place. Because we test with different pod versions. We’ve seen a difference with CocoaPods 1.9.3 and 1.10.1, both builds failing in a different way. The pod's versions 1.10.0 and 1.10.1 def remove the embed stage.

**Comment by mikehardy** [comment]
Okay, we're on the path then - cocoapods 1.10+ should work, if the build is failing that will be something different, as mentioned the notifee-demo.sh script is a reproduction builder, it starts from scratch and works, so we're pretty confident in the module (barring something subtle). I suspect this is something project-specific then

**Comment by DanielMarkiel** [comment]
Hi,

We experience a similar issue in our project which results in the following error:

```
⚠️  ld: ignoring file [project-path]/node_modules/@notifee/react-native/ios/NotifeeCore.xcframework/ios-arm64_armv7/NotifeeCore.framework/NotifeeCore, missing required architecture x86_64 in file [project-path]/node_modules/@notifee/react-native/ios/NotifeeCore.xcframework/ios-arm64_armv7/NotifeeCore.framework/NotifeeCore (2 slices)
⚠️  ld: Could not find or use auto-linked framework 'GoogleDataTransport'
⚠️  ld: Could not find or use auto-linked framework 'FirebaseRemoteConfig'
⚠️  ld: Could not find or use auto-linked framework 'FirebaseCore'
⚠️  ld: Could not find or use auto-linked framework 'GoogleUtilities'
⚠️  ld: Could not find or use auto-linked framework 'FirebaseInstallations'
⚠️  ld: Could not find or use auto-linked framework 'Protobuf'
⚠️  ld: Could not find or use auto-linked framework 'GoogleToolboxForMac'

❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The last working version of `@notifee/react-native` for us is `0.15.2`.
We're using xcode 12.3 and cocoapods 1.9.3.
I can confirm that the upgrade to cocoapods 1.10.1 fixes the above but unfortunately we can't do it because of another issue (with a different package) which results in a malformed archive.

Is there any chance that `@notifee/react-native` package will support cocoapods 1.9.3 again?

**Comment by mikehardy** [comment]
There is no chance this module will support cocoapods 1.9. The changes in 1.10 are required to support Apple Silicon macs and mac catalyst builds, so unfortunately you'll have to stay on the prior version of notifee while pursuing the other module vendor(s) to make themselves compatible with 1.10.x. This is unfortunate but it's a major architectural change internal in packaging and there's no way around it for us to support arm64 as a host machine (Apple Silicon)

**Comment by mikehardy** [comment]
I think the correct action here is to bump the cocoapods requirement - like so:
https://github.com/invertase/firestore-ios-sdk-frameworks/pull/22/files

.. possibly with a documentation mention

**Comment by mikehardy** [comment]
@DanielMarkiel as a note, if the "other package" was mapbox, they have a v2 in preview which I think will work with cocoapods v1.10+

**Comment by DanielMarkiel** [comment]
@mikehardy Yes, it was mapbox and I can confirm that the latest version is finally working with cocoapods v1.10+ so we were able to upgrade `react-native-notifee` to the latest version as well.

**Comment by mikehardy** [comment]
Fantastic news. I'm actually positive on the Apple Silicon thing in general, but it has been very ecosystem-disruptive... thanks for your patience
